#' Returns List of Requested Channel Videos
#'
#' Retrieves items from a channel's uploads playlist.
#'
#' @param channel_id String. ID of the channel. Required.
#' @param max_results Maximum total number of videos returned.
#' @param page_token  Specific page in the result set that should be returned.
#' Optional.
#' @param simplify If `TRUE`, return a data frame; otherwise return the raw
#' playlist-items response.
#' @param auth Authentication method, `"key"` or `"token"`.
#' @param \dots Additional arguments passed to \code{\link{tuber_GET}}.
#'
#' @return A data frame when `simplify = TRUE`; otherwise a playlist-items
#' response.
#'
#' @export
#'
#' @references \url{https://developers.google.com/youtube/v3/docs/channels/list}
#'
#' @examples
#'
#' \dontrun{
#'
#' # Set API token via yt_oauth() first
#'
#' list_channel_videos(channel_id = "UCXOKEdfOFxsHO_-Su3K8SHg")
#' list_channel_videos(channel_id = "UCXOKEdfOFxsHO_-Su3K8SHg", max_results = 10)
#' }

list_channel_videos <- function(channel_id,
                                max_results = 50,
                                page_token = NULL,
                                simplify = TRUE,
                                auth = "key",
                                ...) {

  # Modern validation using checkmate
  assert_character(channel_id, len = 1, min.chars = 1, .var.name = "channel_id")
  assert_integerish(max_results, len = 1, lower = 1, .var.name = "max_results")
  assert_flag(simplify, .var.name = "simplify")
  assert_choice(auth, c("key", "token"), .var.name = "auth")

  if (!is.null(page_token)) {
    assert_character(page_token, len = 1, min.chars = 1, .var.name = "page_token")
  }

  # Validate and convert channel ID to uploads playlist ID
  if (grepl("^UC", channel_id) && nchar(channel_id) == 24) {
    # Standard channel: UC... -> UU...
    playlist_id <- paste0("UU", substr(channel_id, 3, nchar(channel_id)))
  } else if (grepl("^UU", channel_id) && nchar(channel_id) == 24) {
    # Already an uploads playlist ID
    playlist_id <- channel_id
    warn("Provided ID appears to be an uploads playlist ID, using directly",
         class = "tuber_playlist_id_detected")
  } else {
    # Try to get the uploads playlist ID via API
    tryCatch({
      channel_info <- tuber_GET("channels",
                                list(part = "contentDetails,snippet", id = channel_id),
                                auth = auth,
                                ...)

      if (length(channel_info$items) == 0) {
        abort("Channel not found",
              channel_id = channel_id,
              help = "This may be a brand channel, deleted channel, or invalid ID.",
              class = "tuber_channel_not_found")
      }

      playlist_id <- channel_info$items[[1]]$contentDetails$relatedPlaylists$uploads

      if (is.null(playlist_id)) {
        # Check if this is an autogenerated channel
        channel_title <- if (is.null(channel_info$items[[1]]$snippet$title)) "Unknown" else channel_info$items[[1]]$snippet$title
        is_auto_generated <- grepl("Topic$|Auto-generated", channel_title, ignore.case = TRUE)

        error_msg <- paste("Unable to find uploads playlist for channel:", channel_id)
        if (is_auto_generated) {
          error_msg <- paste(error_msg,
                            "\nThis appears to be an auto-generated channel (e.g., music topic channel).",
                            "\nAuto-generated channels don't have traditional uploads playlists.",
                            "\nTry using yt_search() with channel_id parameter instead:")
          error_msg <- paste(error_msg,
                            sprintf('\nyt_search(term = "", channel_id = "%s", max_results = %d)',
                                   channel_id, max_results))
        } else {
          error_msg <- paste(error_msg, "\nThis channel may not have any uploaded videos.")
        }

        abort(error_msg,
              channel_id = channel_id,
              class = if (is_auto_generated) "tuber_autogenerated_channel" else "tuber_no_uploads_playlist")
      }

    }, error = function(e) {
      abort("Failed to resolve channel ID",
            channel_id = channel_id,
            original_error = e$message,
            help = "Supported formats: 24-character UC... channel IDs, or 24-character UU... playlist IDs",
            class = "tuber_channel_resolution_error")
    })
  }

  # Get videos from the uploads playlist
  videos <- list_playlist_items(playlist_id = playlist_id,
                               max_results = max_results,
                               page_token = page_token,
                               simplify = simplify,
                               auth = auth,
                               ...)

  # Add note about unlisted videos
  if (is.list(videos) && !is.null(videos$items) && length(videos$items) > 0) {
    attr(videos, "note") <- paste("Note: Unlisted videos require the channel owner's OAuth token",
                                 "and may not appear in public playlist results.")
  }

  if (!inherits(videos, "tuber_result")) {
    videos <- add_tuber_attributes(
      videos,
      function_name = "list_channel_videos",
      parameters = list(channel_id = channel_id, max_results = max_results),
      results_found = if (is.data.frame(videos)) nrow(videos) else length(videos$items)
    )
  }

  videos
}
